version: '3'
services: 
    mongo:
        image: 'mongo'
        container_name: 'posts_mongo_db'
        environment: 
            - MONGO_INITDB_DATABASE=posts
            - MONGO_INITDB_ROOT_USERNAME=postsAdmin
            - MONGO_INITDB_ROOT_PASSWORD=postsAdminPw
        volumes: 
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongo_volume:/data/db
        ports:
            - '27017-27019:27017-27019'